"""Local telemetry from a B-Infohub bridge over the ESPHome native API.

WHY THIS EXISTS

EnergyTrak is a cloud service. Its equipment snapshot is a batch upload, not a
live feed -- on a cellular unit it can be hours or months old, which
``normalize.py`` already goes to some length to detect and discount. A local
RS-485 bridge sitting on the generator's own Modbus port sees the controller
directly, every ten seconds, and reads roughly twice as many registers as the
cloud ever exposed.

So when such a bridge is reachable, it is a strictly better source, and this
module supplies it.

OPTIONAL BY CONSTRUCTION

Almost nobody running this integration owns one of these bridges. Nothing here
is imported unless a local bridge has actually been configured, no entity is
created for a field the bridge does not report, and a bridge that goes away
simply stops overriding -- the cloud values are still being fetched underneath
the whole time. A cloud-only install behaves exactly as it did before.

WHY NOT JUST ADD THE ESPHOME INTEGRATION

Home Assistant's own ESPHome integration would happily adopt the bridge and
create its ~160 entities. That is the problem: you would then have two
generator devices, two ``battery_voltage`` sensors, and dashboards bound to
whichever one you picked first. Owning the connection here means one device,
one set of entities, and a source that changes underneath them silently.

THE THREE-STATE LIVENESS PROBLEM

"Is the bridge reachable" is not the question. There are three states:

    connected, bus healthy  -> use local
    connected, bus DEAD     -> use cloud   <- the one that bites
    disconnected            -> use cloud

The middle case is why ``bus_healthy`` is consulted and not merely the socket.
A bridge whose RS-485 has failed -- unplugged, controller powered down, wrong
baud after an edit -- stays connected, keeps answering, and keeps serving its
last good readings. Those readings look exactly like a healthy idle generator:
zero output, engine stopped, no alarms. Nothing in the values themselves says
"these are frozen". Trusting the socket alone would silently replace good cloud
data with a plausible lie.
"""

from __future__ import annotations

import asyncio
import inspect
import json
import logging
from time import monotonic
import pathlib
from typing import Any, Callable

from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.event import async_call_later

_LOGGER = logging.getLogger(__name__)

_CONTRACT_PATH = pathlib.Path(__file__).parent / "telemetry_contract.json"


def load_alarm_names() -> list[str]:
    """Alarm index -> display name. Blocking; call from an executor."""
    try:
        return json.loads(
            (pathlib.Path(__file__).parent / "alarm_index.json").read_text()
        )["index"]
    except Exception:  # noqa: BLE001
        return []


def load_contract() -> dict[str, Any]:
    """Read the firmware's published telemetry contract.

    Generated by the B-Infohub repo (contract/gen.py) and copied in here, so
    the register map, the key names and the object_ids all come from one place.
    Hand-maintaining this mapping would drift the first time a register moved.
    """
    return json.loads(_CONTRACT_PATH.read_text())


# A shared key must be drop-in compatible with the cloud's VALUE, not merely
# with its name. Entity ids survive a source switch so that dashboards and
# alert rules need no changes -- but that promise is only kept if the state
# they read means the same thing afterwards.
#
# Measured on production at the moment the bridge took over:
#
#   operation_mode   "AUTO"     ->  "Automatic"
#   ignition_status   0         ->  "Stopped"
#
# Neither is wrong; both are a different vocabulary for the same fact. The
# damage is downstream and silent. B-Panels matches operation_mode as a string,
# the Grafana push carries it as a TAG (so a changed value starts a brand new
# series and the old one flatlines rather than erroring), and the ignition
# gauge maps on/true/1 and off/false/0 -- "Stopped" matches neither arm, so the
# metric was simply omitted and the panel went blank.
#
# So the bridge's richer vocabulary is folded back to the cloud's on the way
# out. The full text stays available on the local-only entities
# (switch_status, engine_state), which is where you would look for it.
_SHARED_TEXT_ALIASES: dict[str, dict[str, Any]] = {
    "operation_mode": {
        "automatic": "AUTO",
        "manual": "MANUAL",
        "off": "OFF",
        "test": "TEST",
    },
    "ignition_status": {
        "running": 1,
        "starting": 1,
        "stopped": 0,
        "stopping": 0,
        "off": 0,
    },
}


def _to_cloud_vocabulary(key: str, value: Any) -> Any:
    """Translate a bridge value into the cloud's representation of that key."""
    table = _SHARED_TEXT_ALIASES.get(key)
    if table is None or not isinstance(value, str):
        return value
    return table.get(value.strip().lower(), value)


# Readings that must not wait for the coordinator's interval.
#
# The alarm bits come from the contract. These are the non-alarm state changes
# that are just as time-critical, and they are listed rather than inferred
# because "is this urgent" is a judgement about consequences, not a property of
# the register:
#
#   utility_power_failure  the outage itself -- the event the whole system
#                          exists to notice, and the one a 30s delay makes
#                          look like the monitoring failed
#   engine_state           starting / running / stopped transitions
#   engine_running
#   engine_starting        the earliest evidence of a start attempt, and the
#                          leading edge of a failed one
#   switch_status          somebody moved AUTO/MANUAL/OFF at the panel; in OFF
#                          the generator will not answer an outage at all
#   common_shutdown        the machine has tripped
#
# Everything else -- voltages, currents, temperatures, hour meters -- rides the
# normal interval. Those change on every poll of an 87-register bus, so waking
# the coordinator for each would be a refresh storm that buys nothing: nobody
# needs battery voltage 20 seconds sooner.
_URGENT_EXTRA: frozenset[str] = frozenset({
    "utility_power_failure",
    "engine_state",
    "engine_running",
    "engine_starting",
    "switch_status",
    "common_shutdown",
})

# A start asserts several bits within a few hundred milliseconds. Firing per
# bit would rebuild and publish the payload half a dozen times for one event.
# This is short enough to stay immediate in human terms and long enough to
# collapse a burst into one update.
_URGENT_COALESCE_SECONDS = 0.35

# How long the bridge may say nothing at all before its cached readings stop
# being treated as current. See LocalBridge.available.
RX_SILENCE_LIMIT = 120.0


# Contract kind -> the aioesphomeapi class the bridge must report it as. Matched
# by name so this module still imports nothing from aioesphomeapi at load time.
_INFO_CLASS = {
    "number": "NumberInfo",
    "switch": "SwitchInfo",
    "text": "TextInfo",
    "button": "ButtonInfo",
}


class LocalBridgeUnavailable(Exception):
    """Raised when the bridge cannot be reached or does not look like ours."""


class LocalBridge:
    """A live subscription to one B-Infohub bridge.

    Values are pushed, not polled: ``subscribe_states`` fires on change, so the
    cached snapshot is always current and ``snapshot()`` costs nothing.

    For most readings the coordinator's interval then governs how often Home
    Assistant is told, which keeps the cloud and local paths on one cadence.
    Battery voltage arriving 20 seconds late costs nothing.

    URGENT READINGS DO NOT WAIT FOR THAT INTERVAL. A utility failure, a start,
    or a shutdown alarm reaches this object within milliseconds and then used
    to sit in _values until the next poll -- up to a full scan_interval of
    invented delay on the events that matter most, on a transport that had
    already delivered them. Those fire async_add_urgent_listener immediately
    instead, coalesced over a short window because a single start sets several
    bits at once.
    """

    def __init__(
        self,
        hass: HomeAssistant,
        host: str,
        port: int,
        encryption_key: str | None,
        contract: dict[str, Any] | None = None,
    ) -> None:
        """Prepare a bridge client; no I/O happens until async_start."""
        self.hass = hass
        self.host = host
        self.port = port
        self._encryption_key = encryption_key
        # NOT loaded here. __init__ runs on the event loop, and Home Assistant
        # raises on blocking file I/O there rather than just warning about it.
        # Deferred to async_start, which can use an executor.
        self._contract: dict[str, Any] | None = contract

        # Fired the moment a significant reading CHANGES, rather than on the
        # coordinator's interval. See _URGENT_EXTRA and _on_state.
        # Wall-clock of the last state message of ANY kind. See `available`.
        self._last_rx: float = 0.0
        self._urgent_listeners: list[Callable[[], None]] = []
        self._urgent_oids: frozenset[str] = frozenset()
        self._urgent_timer: Any = None

        # numeric API key -> object_id, learned from list_entities on connect
        self._keys: dict[int, str] = {}
        # object_id -> latest value
        self._values: dict[str, Any] = {}
        self._connected = False
        self._services: dict[str, Any] = {}
        # object_id -> the bridge's NumberInfo, for the settings the contract
        # allows Home Assistant to change. See _learn_controls.
        self._controls: dict[str, Any] = {}
        self._device_info: Any = None
        self._client: Any = None
        self._reconnect: Any = None
        self._listeners: list[Callable[[], None]] = []

        self._health_oid = "bus_healthy"
        self._age_oid = "bus_age"
        self._map: dict[str, str] = {}
        self._alarm_oids: list[str] = []
        if self._contract is not None:
            self._build_maps()

    def _build_maps(self) -> None:
        """Derive the object_id lookups once the contract is in hand."""
        live = self._contract["liveness"]
        self._health_oid = live["api_health_object_id"]
        self._age_oid = live["api_age_object_id"]
        self._map = {
            meta["object_id"]: key
            for key, meta in self._contract["shared_keys"].items()
        }
        self._map.update(
            {meta["object_id"]: key
             for key, meta in self._contract["local_only_keys"].items()}
        )
        self._alarm_oids = list(self._contract["alarm_keys"])
        # exercising / scheduled_exercise_in_progress are in alarm_keys but are
        # run states, not faults. They still belong here: knowing a run is a
        # scheduled exercise is what lets a consumer NOT treat it as an
        # incident, and that distinction is only useful if it arrives with the
        # start rather than 30 seconds after it.
        self._urgent_oids = frozenset(self._alarm_oids) | _URGENT_EXTRA

    # ------------------------------------------------------------------ life
    async def async_start(self) -> None:
        """Connect and stay connected, retrying in the background."""
        if self._contract is None:
            self._contract = await self.hass.async_add_executor_job(load_contract)
            self._build_maps()

        # Imported here, not at module scope: a cloud-only install must never
        # pay for -- or fail on -- a dependency it has no use for.
        from aioesphomeapi import APIClient, ReconnectLogic

        self._client = APIClient(
            self.host,
            self.port,
            password=None,
            noise_psk=self._encryption_key or None,
            client_info="ha-energytrak",
        )

        async def _on_connect() -> None:
            try:
                # Identity for the Home Assistant device card. On a bridge-only
                # install there is no cloud site document to take a name from,
                # so this is the only source of one.
                self._device_info = await self._client.device_info()
                entities, services = await self._client.list_entities_services()
            except Exception as err:  # noqa: BLE001 - reconnect logic handles it
                _LOGGER.debug("Local bridge list_entities failed: %s", err)
                raise
            self._keys = {}
            for group in entities:
                for ent in group if isinstance(group, list) else [group]:
                    oid = getattr(ent, "object_id", None)
                    key = getattr(ent, "key", None)
                    if oid is not None and key is not None:
                        self._keys[key] = oid
            # THIS LINE IS WHY EVERY ACKNOWLEDGEMENT SILENTLY FAILED.
            #
            # The services half of list_entities_services() was being bound to a
            # local named `_services` -- the underscore that conventionally
            # means "discard". self._services therefore stayed {} for the life
            # of the connection, async_call() hit its `svc is None` guard and
            # returned False every single time, and backlog_ack never once left
            # the process.
            #
            # The symptom is nasty because nothing errors: the drain replays a
            # batch, fails to acknowledge it, and replays the SAME batch on the
            # next poll, forever. With alarms in that batch it is a critical
            # notification every thirty seconds about an event that already
            # finished. Seen in the field before it was seen in review.
            self._services = {
                svc.name: svc
                for svc in (services or [])
                if getattr(svc, "name", None)
            }
            _LOGGER.debug(
                "Local bridge exposes %d action(s): %s",
                len(self._services), ", ".join(sorted(self._services)) or "none",
            )

            self._learn_controls(entities)

            self._client.subscribe_states(self._on_state)
            self._connected = True
            _LOGGER.info(
                "Local B-Infohub bridge connected at %s (%d entities)",
                self.host,
                len(self._keys),
            )
            self._notify()

        async def _on_disconnect(expected_disconnect: bool) -> None:
            self._connected = False
            # Values are deliberately NOT cleared. If the bridge drops for one
            # poll the coordinator falls back to cloud anyway (see snapshot),
            # and keeping them makes reconnection seamless rather than
            # flapping every entity through "unknown".
            if not expected_disconnect:
                _LOGGER.warning("Local B-Infohub bridge disconnected")
            self._notify()

        self._reconnect = ReconnectLogic(
            client=self._client,
            on_connect=_on_connect,
            on_disconnect=_on_disconnect,
            zeroconf_instance=None,
            name=f"b-infohub@{self.host}",
        )
        await self._reconnect.start()

        # ReconnectLogic.start() returns immediately and connects in the
        # background. Without waiting, the coordinator's first refresh runs
        # against a bridge that is reachable but not yet connected, decides the
        # entry has failed, and retries -- building a NEW bridge each time, so
        # it never gets far enough to succeed. A permanent retry loop caused by
        # nothing but impatience.
        #
        # Not fatal if it expires: a bridge that is merely slow will connect on
        # its own and the coordinator picks it up on a later refresh.
        try:
            async with asyncio.timeout(15):
                while not self._connected:
                    await asyncio.sleep(0.25)
        except TimeoutError:
            _LOGGER.debug("Bridge at %s not connected within 15s; continuing", self.host)

    async def async_stop(self) -> None:
        """Tear down cleanly on unload."""
        if self._reconnect is not None:
            await self._reconnect.stop()
            self._reconnect = None
        if self._client is not None:
            await self._client.disconnect()
            self._client = None
        self._connected = False

    @callback
    def async_add_listener(self, cb: Callable[[], None]) -> Callable[[], None]:
        """Register a callback fired whenever connection state changes."""
        self._listeners.append(cb)

        def _remove() -> None:
            if cb in self._listeners:
                self._listeners.remove(cb)

        return _remove

    def _notify(self) -> None:
        for cb in list(self._listeners):
            try:
                cb()
            except Exception:  # noqa: BLE001
                _LOGGER.exception("Local bridge listener failed")

    # ----------------------------------------------------------------- state
    @callback
    def async_add_urgent_listener(
        self, cb: Callable[[], None]
    ) -> Callable[[], None]:
        """Register a callback fired when an URGENT reading changes.

        Separate from async_add_listener, which is about the connection going
        up or down. This one is about the generator doing something.
        """
        self._urgent_listeners.append(cb)

        def _remove() -> None:
            if cb in self._urgent_listeners:
                self._urgent_listeners.remove(cb)

        return _remove

    @callback
    def _fire_urgent(self) -> None:
        """Run the urgent callbacks once, after the coalesce window."""
        self._urgent_timer = None
        for cb in list(self._urgent_listeners):
            try:
                cb()
            except Exception:  # noqa: BLE001
                _LOGGER.exception("Urgent bridge listener failed")

    @callback
    def _schedule_urgent(self) -> None:
        """Start (but do not restart) the coalesce window.

        Deliberately NOT a debounce that pushes the deadline back on every
        new bit. A cascade of alarms during a hard fault would keep resetting
        it and delay the notification for exactly as long as the emergency
        lasted. The first urgent change starts the clock and the clock does
        not move; later bits inside the window ride along with it.
        """
        if self._urgent_timer is not None:
            return
        self._urgent_timer = async_call_later(
            self.hass, _URGENT_COALESCE_SECONDS, lambda _now: self._fire_urgent()
        )

    @callback
    def _on_state(self, state: Any) -> None:
        oid = self._keys.get(getattr(state, "key", None))
        if oid is None:
            return
        # missing_state means the device has the entity but no reading yet --
        # an unpopulated register, not a zero.
        self._last_rx = monotonic()
        if getattr(state, "missing_state", False):
            if self._values.pop(oid, None) is not None and oid in self._urgent_oids:
                self._schedule_urgent()
            return

        value = getattr(state, "state", None)
        had = oid in self._values
        previous = self._values.get(oid)
        self._values[oid] = value
        self._last_rx = monotonic()

        # Only on an actual CHANGE. ESPHome republishes on every poll of the
        # bus, so reacting to each message would wake the coordinator several
        # times a second for readings that did not move.
        #
        # `had` matters: the first value for an alarm arrives during startup,
        # when every bit goes from absent to False. That is not a transition
        # to anything, and treating it as one is how the firmware's own event
        # log once logged a storm of phantom alarms on connect.
        if had and value != previous and oid in self._urgent_oids:
            self._schedule_urgent()

    # -------------------------------------------------------------- snapshot
    @property
    def connected(self) -> bool:
        """Whether the API socket is up. NOT sufficient to trust the data."""
        return self._connected

    @property
    def bus_healthy(self) -> bool:
        """Whether the bridge is actually hearing the generator."""
        return bool(self._values.get(self._health_oid))

    @property
    def bus_age(self) -> float | None:
        """Seconds since a register last arrived, per the bridge."""
        value = self._values.get(self._age_oid)
        return float(value) if isinstance(value, (int, float)) else None

    @property
    def rx_age(self) -> float | None:
        """Seconds since ANY state message arrived, or None if none ever has."""
        if not self._last_rx:
            return None
        return monotonic() - self._last_rx

    @property
    def available(self) -> bool:
        """True only in the one state where local data may be trusted.

        SILENCE MUST NOT COUNT AS GOOD DATA.

        `connected` means a TCP socket is open, which is a much weaker claim
        than it looks: a wedged ESP32 can hold the socket open while publishing
        nothing, and every cached reading then sits in Home Assistant looking
        like a healthy idle generator -- 0 kW, not running, no alarms. Nothing
        about those values says "stale". `bus_healthy` does not save us either,
        because it is itself a value FROM the bridge, so it freezes with
        everything else.

        So freshness is asserted the one way that cannot be faked: time since a
        message of ANY kind last arrived. The bridge publishes continuously --
        measured on this hardware, battery voltage alone lands 8 times a minute
        and a poll cycle touches dozens of entities -- so RX_SILENCE_LIMIT of
        two minutes is far outside normal and only reachable if the device has
        genuinely stopped talking.

        Deliberately counts MESSAGES, not value changes. Most readings on an
        idle generator never change, and requiring change would declare a
        perfectly healthy bus dead every time the machine sat still.
        """
        if not self._connected or not self.bus_healthy:
            return False
        age = self.rx_age
        if age is None:
            return False
        if age > RX_SILENCE_LIMIT:
            _LOGGER.warning(
                "Local bridge at %s is connected but has sent nothing for %.0fs; "
                "treating its data as stale rather than current",
                self.host, age,
            )
            return False
        return True

    def snapshot(self) -> dict[str, Any] | None:
        """Flat telemetry dict in normalize.py's shape, or None if untrusted.

        Returning None rather than a partial dict is deliberate: a caller that
        has to decide per-field whether local is trustworthy will eventually
        get it wrong somewhere. The trust decision is made once, here.
        """
        if not self.available:
            return None

        out: dict[str, Any] = {}
        for oid, key in self._map.items():
            if oid in self._values:
                value = self._values[oid]
                # ESPHome sends NaN for a sensor with no reading; JSON and the
                # HA state machine both want it gone rather than propagated.
                if isinstance(value, float) and value != value:
                    continue
                # Modbus gives far more precision than the sensor has. Raw
                # floats (13.100000381469727 for a 0.1V reading) are ugly in
                # the UI, bloat the recorder, and make every long-term
                # statistic a distinct value. The cloud sent 13.1; match it.
                if isinstance(value, float):
                    value = round(value, 3)
                out[key] = _to_cloud_vocabulary(key, value)

        out.update(self._derive())
        out["telemetry_source"] = "local"
        out["local_bus_age_seconds"] = self.bus_age
        return out

    def device_identity(self) -> dict[str, Any]:
        """Device-card fields, for an install with no cloud document.

        Deliberately NOT part of snapshot(). The coordinator overlays the
        snapshot on top of the cloud payload, so anything in it wins -- and
        these fields must lose. EnergyTrak knows the real serial number, model
        and site name; the Modbus map carries none of them. These are applied
        with setdefault, to fill blanks on a bridge-only install and to change
        nothing at all for a user who has both.
        """
        info = self._device_info
        out: dict[str, Any] = {
            "make": "Briggs & Stratton",
            "model": "GC-1032",
        }
        if info is not None:
            out["name"] = getattr(info, "friendly_name", None) or getattr(info, "name", None)
            out["firmware_version"] = getattr(info, "project_version", None) or getattr(
                info, "esphome_version", None
            )
            if mac := getattr(info, "mac_address", None):
                out["serial_number"] = mac
        return out

    async def async_call(self, name: str, **kwargs: Any) -> bool:
        """Invoke a user-defined action on the bridge.

        Returns False rather than raising when the action is unknown: a bridge
        running older firmware simply has no backlog to drain, and that is a
        normal state, not an error.
        """
        svc = self._services.get(name)
        if svc is None or self._client is None or not self._connected:
            return False
        try:
            # execute_service is a COROUTINE. Calling it without awaiting
            # returns a coroutine object, does nothing, and raises no error --
            # it only surfaces as a RuntimeWarning on garbage collection. The
            # symptom is a backlog that replays the same record forever
            # because the acknowledgement never leaves the process.
            result = self._client.execute_service(svc, kwargs)
            if inspect.isawaitable(result):
                await result
        except Exception as err:  # noqa: BLE001
            _LOGGER.debug("Bridge action %s failed: %s", name, err)
            return False
        return True

    # -------------------------------------------------------------- controls
    def _learn_controls(self, entities: Any) -> None:
        """Remember the writable settings this bridge actually has.

        ONLY those named in the contract's `controls`, and only when the
        bridge reports them as the kind the contract says they are. The bridge
        has other writable entities -- Wi-Fi credentials, factory reset -- and
        the allowlist is enforced here as well as in the firmware's contract
        generator, so a stale or hand-edited contract cannot widen what Home
        Assistant can touch. A bridge on older firmware simply reports fewer
        of them, and no entity is created for the rest.
        """
        allowed = (self._contract or {}).get("controls", {})
        self._controls = {}
        for group in entities or []:
            for ent in group if isinstance(group, list) else [group]:
                oid = getattr(ent, "object_id", None)
                meta = allowed.get(oid)
                if meta and type(ent).__name__ == _INFO_CLASS.get(meta["kind"]):
                    self._controls[oid] = ent

    @property
    def controls(self) -> dict[str, dict[str, Any]]:
        """Contract metadata for every control this bridge has reported."""
        allowed = (self._contract or {}).get("controls", {})
        return {oid: allowed[oid] for oid in self._controls if oid in allowed}

    async def async_control(self, object_id: str, value: Any = None) -> bool:
        """Set one allowed control, or press it. False if it was not sent."""
        info = self._controls.get(object_id)
        meta = self.controls.get(object_id)
        if info is None or meta is None or self._client is None or not self._connected:
            return False
        kind = meta["kind"]
        try:
            if kind == "number":
                value = float(value)
                result = self._client.number_command(info.key, value)
            elif kind == "switch":
                value = bool(value)
                result = self._client.switch_command(info.key, value)
            elif kind == "text":
                value = str(value)
                result = self._client.text_command(info.key, value)
            elif kind == "button":
                result = self._client.button_command(info.key)
            else:
                return False
            # These are synchronous in current aioesphomeapi, but have been
            # coroutines before -- see the execute_service note in async_call
            # for what an un-awaited one does, which is nothing.
            if inspect.isawaitable(result):
                await result
        except Exception as err:  # noqa: BLE001
            _LOGGER.debug("Bridge control %s failed: %s", object_id, err)
            return False
        # Show the new value now rather than on the next coordinator refresh.
        # The bridge echoes its real state straight back through _on_state,
        # which corrects this if it clamped or refused the value.
        if kind != "button":
            self._values[object_id] = value
        return True

    def raw(self, object_id: str) -> Any:
        """Latest value of one entity by object_id, or None."""
        return self._values.get(object_id)

    @property
    def mac(self) -> str | None:
        """MAC address, once connected. Stable identity across DHCP changes."""
        return getattr(self._device_info, "mac_address", None) if self._device_info else None

    def _derive(self) -> dict[str, Any]:
        """Compute the keys that are not registers.

        The MQTT path computes these in a C++ lambda on the device. The native
        API has no such hook -- it carries raw entities only -- so the same
        derivations are declared transport-neutrally in the contract and
        executed here. Keeping the spec in the contract is what stops the two
        transports drifting into disagreeing about what `grid_present` means.
        """
        out: dict[str, Any] = {}
        for key, spec in self._contract["derived"].items():
            op = spec["op"]
            if op == "const":
                out[key] = spec["value"]
                continue
            if op in ("count_true", "join_true"):
                asserted = [
                    oid for oid in self._alarm_oids if bool(self._values.get(oid))
                ]
                if op == "count_true":
                    out[key] = len(asserted)
                else:
                    names = [self._pretty(oid) for oid in asserted]
                    out[key] = ", ".join(names) if names else spec.get("empty", "None")
                continue

            src = spec["src"]
            if src not in self._values:
                continue
            value = self._values[src]
            if op == "not":
                out[key] = not bool(value)
            elif op == "copy":
                out[key] = value
            elif op == "map_bool":
                out[key] = spec["true"] if bool(value) else spec["false"]
        return out

    def _pretty(self, object_id: str) -> str:
        meta = self._contract["local_only_keys"].get(object_id)
        if meta and meta.get("name"):
            return meta["name"]
        return object_id.replace("_", " ").title()
