#!/usr/bin/env python3
"""Generate the local-bridge entity descriptions from the firmware contract.

    python3 scripts/gen_local_entities.py [path/to/B-Infohub/contract/telemetry.json]

The B-Infohub bridge reads ~100 registers the EnergyTrak cloud has never
exposed -- L3 phases, line-to-line voltages, oil pressure, coolant, fuel,
cumulative energy and 43 discrete alarms. Hand-writing an EntityDescription for
each is busywork that goes stale the moment the firmware gains a register.

So the firmware publishes contract/telemetry.json, and this writes:

    custom_components/energytrak/local_entities.py
    (plus the matching strings into translations/en.json)

Never edit the generated file. Change the firmware contract and re-run.
"""
from __future__ import annotations
import json, pathlib, sys, re

HERE = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_CONTRACT = HERE.parent / "B-Infohub" / "contract" / "telemetry.json"
contract_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CONTRACT
if not contract_path.exists():
    sys.exit(f"contract not found: {contract_path}\nPass its path as the first argument.")
C = json.loads(contract_path.read_text())

# unit string from ESPHome -> (HA unit constant, device class, state class, precision)
UNITS = {
    "V":     ("UnitOfElectricPotential.VOLT",     "VOLTAGE",         "MEASUREMENT", 1),
    "A":     ("UnitOfElectricCurrent.AMPERE",     "CURRENT",         "MEASUREMENT", 1),
    "Hz":    ("UnitOfFrequency.HERTZ",            "FREQUENCY",       "MEASUREMENT", 2),
    "kW":    ("UnitOfPower.KILO_WATT",            "POWER",           "MEASUREMENT", 2),
    "kVA":   ("UnitOfApparentPower.VOLT_AMPERE",  "APPARENT_POWER",  "MEASUREMENT", 2),
    "kvar":  (None,                                "REACTIVE_POWER",  "MEASUREMENT", 2),
    "kWh":   ("UnitOfEnergy.KILO_WATT_HOUR",      "ENERGY",          "TOTAL_INCREASING", 1),
    "kVAh":  (None,                                None,              "TOTAL_INCREASING", 1),
    "kvarh": (None,                                None,              "TOTAL_INCREASING", 1),
    "RPM":   ("REVOLUTIONS_PER_MINUTE",           None,              "MEASUREMENT", 0),
    "%":     ("PERCENTAGE",                       None,              "MEASUREMENT", 0),
    "bar":   ("UnitOfPressure.BAR",               "PRESSURE",        "MEASUREMENT", 2),
    "psi":   ("UnitOfPressure.PSI",               "PRESSURE",        "MEASUREMENT", 1),
    "°C":    ("UnitOfTemperature.CELSIUS",        "TEMPERATURE",     "MEASUREMENT", 1),
    "L":     ("UnitOfVolume.LITERS",              "VOLUME_STORAGE",  "MEASUREMENT", 1),
    "h":     ("UnitOfTime.HOURS",                 "DURATION",        "TOTAL_INCREASING", 1),
    "s":     ("UnitOfTime.SECONDS",               "DURATION",        "MEASUREMENT", 0),
}

def title(key: str, given: str | None) -> str:
    return given or key.replace("_", " ").title()

nums, bins, txts, strings = [], [], [], {}
for key, meta in C["local_only_keys"].items():
    strings[key] = title(key, meta.get("name"))
    kind, unit = meta["kind"], meta.get("unit")
    if kind == "bin":
        bins.append((key, meta))
    elif kind == "txt":
        txts.append((key, meta))
    else:
        nums.append((key, meta, UNITS.get(unit or "", (None, None, "MEASUREMENT", 2))))

def sensor_block(key, meta, u):
    unit_c, dev, state, prec = u
    L = [f'    EnergyTrakSensorDescription(', f'        key="{key}",',
         f'        translation_key="{key}",']
    if dev:    L.append(f"        device_class=SensorDeviceClass.{dev},")
    if unit_c: L.append(f"        native_unit_of_measurement={unit_c},")
    elif meta.get("unit"): L.append(f'        native_unit_of_measurement="{meta["unit"]}",')
    if state:  L.append(f"        state_class=SensorStateClass.{state},")
    L += [f"        suggested_display_precision={prec},",
          "        entity_registry_enabled_default=False," if meta.get("unit") is None else "",
          f'        value_fn=_key("{key}"),', "    ),"]
    return "\n".join(x for x in L if x)

out = ['"""GENERATED by scripts/gen_local_entities.py -- DO NOT EDIT.',
 "",
 "Entity descriptions for readings that exist ONLY on the local B-Infohub",
 "bridge. The EnergyTrak cloud has never carried any of these; they appear",
 "only while the bridge is reachable, which is why every one of them is",
 f"created through async_setup_reported_entities rather than unconditionally.",
 "",
 f"Source contract: schema {C['schema']}, {len(C['local_only_keys'])} local-only keys.",
 '"""',
 "from __future__ import annotations", "",
 "from homeassistant.components.binary_sensor import (",
 "    BinarySensorDeviceClass,", ")",
 "from homeassistant.components.sensor import (",
 "    SensorDeviceClass,", "    SensorStateClass,", ")",
 "from homeassistant.const import (",
 "    PERCENTAGE,", "    REVOLUTIONS_PER_MINUTE,", "    UnitOfApparentPower,",
 "    UnitOfElectricCurrent,", "    UnitOfElectricPotential,", "    UnitOfEnergy,",
 "    UnitOfFrequency,", "    UnitOfPower,", "    UnitOfPressure,",
 "    UnitOfTemperature,", "    UnitOfTime,", "    UnitOfVolume,", ")", "",
 "from .binary_sensor import EnergyTrakBinarySensorDescription",
 "from .sensor import EnergyTrakSensorDescription, _key", "", "",
 "LOCAL_SENSORS: tuple[EnergyTrakSensorDescription, ...] = ("]
out += [sensor_block(k, m, u) for k, m, u in nums]
out += [")", "", "",
        "# Discrete faults the controller exposes as individual bits. The cloud",
        "# collapsed all of them into one 'fault' string.",
        "LOCAL_BINARY_SENSORS: tuple[EnergyTrakBinarySensorDescription, ...] = ("]
alarms = set(C["alarm_keys"])
for key, meta in bins:
    dc = "        device_class=BinarySensorDeviceClass.PROBLEM,\n" if key in alarms else ""
    out.append(f'    EnergyTrakBinarySensorDescription(\n        key="{key}",\n'
               f'        translation_key="{key}",\n{dc}'
               f'        value_fn=_key("{key}"),\n    ),')
out += [")", ""]
(HERE / "custom_components/energytrak/local_entities.py").write_text("\n".join(out))

(HERE / "scripts/local_strings.json").write_text(json.dumps(
    {k: {"name": v} for k, v in sorted(strings.items())}, indent=2) + "\n")

print(f"contract schema {C['schema']} from {contract_path}")
print(f"  {len(nums)} sensors, {len(bins)} binary sensors, {len(txts)} text (skipped)")
print(f"  wrote custom_components/energytrak/local_entities.py")
print(f"  wrote scripts/local_strings.json  ({len(strings)} translation names)")
